### ISSUE TITLE
Questão: indicação de servidor

### ISSUE THREAD

**Issue by marceloavf** [macunha1/pontomaisoumenos#4]
Olá,

Primeiramente, obrigado pelo trabalho excepcional neste automatizador,
Gostaria de saber se teria alguma indicação de servidor gratuito ou de baixo custo para utilização deste projeto?

Agradeço!

**Comment by macunha1** [comment]
Olá @marceloavf,

Desculpa pela demora, as notificações no repositório estavam desativadas. Vi seu comentário só agora (e por acaso).

Acho que a escolha do servidor é pessoal, você pode encontrar uma lista de possíveis cloud providers nesse repositório: https://github.com/ripienaar/free-for-dev. Não só para essa aplicação mas também para outros projetos que você estiver desenvolvendo.

Abraços!
